label: Pagination
icon: list
description: "Navigation component for multi-page content."
structures: []
value:
  _component: building-blocks/core-elements/pagination
  page: null
preview:
  text:
    - Pagination
picker_preview:
  text: Pagination
  subtext: "Navigation component for multi-page content."
  icon: list

_inputs:
  page:
    type: object
    comment: The Astro page object from paginate() function.
